# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0011_auto_20160211_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='default_avatar_200x200.png', upload_to=''),
        ),
    ]
