# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_approved', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_pendent', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='projectareas',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectareas',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='projectcontributors',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='projectcontributors',
            name='project',
        ),
        migrations.RemoveField(
            model_name='account',
            name='certification_name',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAreas',
        ),
        migrations.DeleteModel(
            name='ProjectContributors',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
