# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 21:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(2)])),
                ('deleted', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('cover', models.ImageField(default='default_400x400', upload_to='')),
                ('state', models.IntegerField(default=1)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('assets', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('areas', models.ManyToManyField(related_name='project_tags', to='api.Tag')),
                ('contributors', models.ManyToManyField(related_name='project_contributors', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
