# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='areas',
            field=models.ManyToManyField(related_name='areas', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(default='default_400x400.png', upload_to=''),
        ),
    ]
