# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160220_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
