# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160220_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
