# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160211_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inter',
            name='project',
        ),
        migrations.RemoveField(
            model_name='inter',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='areas',
        ),
        migrations.DeleteModel(
            name='Inter',
        ),
    ]
