# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160220_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='target_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
