# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160220_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='is_pendent',
            field=models.BooleanField(default=True),
        ),
    ]
