# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160211_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inter',
            new_name='ProjectAreas',
        ),
        migrations.AlterField(
            model_name='project',
            name='areas',
            field=models.ManyToManyField(through='api.ProjectAreas', to='api.Tag'),
        ),
    ]
