# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_account_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
