# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160211_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='managers',
        ),
        migrations.AddField(
            model_name='projectcontributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
