# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160508_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
