# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160508_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
