# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 23:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_transfer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
