# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160509_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
