# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
