# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_product_is_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_bonus',
            new_name='is_reward',
        ),
    ]
