# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20161010_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
